### ISSUE TITLE
cut / paste modapi

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Lobby#5]
Need to see if there is a way to auto copy the in view grid prior to initiating a connection..

conversely need a way that on connect triggers a client side paste if  player spawns in a space suit on first connecting..

both need to work outside of creative mode..

Be nice if the copied object could have a text string added to the hotspot lcd which is pulled up on pasting to confirm it should be pasted to begin with too..   this allows some level of control over what should be transferred with the paste..

Basically idea is:

1.  player uses a /depart   check if the lcd also has a flag to "travel with ship" if so - prior to initiating the new server connection, check if the travelling player is allowed to take the ship, (owner check?) add some sort of control code to the travel LCD text.   This code could include prefab id, player id,  passenger player IDs (see #6 ), faction, gateway server address etc
1. once the code is generated, trigger a client side copy (or even a cut.. tho that is risky) of whatever ship the player is standing on when they type /depart
1.  If the target server is also running lobby script, on connect if the player chooses the spawn in space suit option immediately after joining, then the lobby script should attempt to paste any ship in the client side paste buffer under the player, on pasting it should check if it has a valid control code, if not then remove the ship again. eg. does the player id match the player that joined, does the originating server code match those permitted on this server
1. if the code is valid,  presumably it also includes the details of the originating server, and adjusts the target IP address of the travel LCD to point back at the server it came from, and any other details needed are processed from the control code and removed from the LCD text  - eg faction is created and players automatically added etc

In theory this means a ship can travel back and forth between a gateway and frontier worlds with the players..  by including passenger data, it may also be possible to teleport all players into the same ship on arrival at a later stage as well

**Comment by midspace** [comment]
No choice but to serialize the ship grids (rotors, pistons, etc) to a shared file, and deserialize them on the new server, and apply new ownership settings.
I'm expecting you are running all servers on the same machine, so they all have access to the same mod storage path, otherwise this will not work.

**Comment by jpcsupplies** [comment]
At the moment my two test servers are physically seperate -
i was hoping some client side trickery might work, but discussions seem to suggest that in practice we cant do a client paste..

local storage will probably work, but that means server side stuff,  my aim here was an entirely client side mod so as to have zero impact on server sim (and i suck at server communication lol)

**Comment by jpcsupplies** [comment]
Not a viable method
